### ISSUE TITLE
Unify Route->defaultFlags and url construction 

### ISSUE THREAD

**Issue by xmedeko** [nette/routing#13]
`Route` has `$defaultFlags` while `SimpleRoute` hasn't. So, it's impossible to set default flags for all routes. 

Also the code for the url protocol construction in both classes are very similar, but different.
- `Route`: `$url = ($this->flags & self::SECURED ? 'https:' : 'http:') . $url;`
- `SimpleRoute`: `$url = ($this->flags & self::SECURED ? 'https://' : 'http://') . $refUrl->getAuthority() . $refUrl->getPath();`

It should be unified and moved into a common method (static, or some common ancestor, or some common shared object, also see #5). The reason is also that custom `IRouter` implementation should benefit from the shared `$defaultFlags` and the url protocol construction and not copy & paste the code.

**Comment by JanTvrdik** [comment]
Shared `$defaultFlags` should be removed. Instead the default behavior should be change to copy the request protocol.

**Comment by dg** [comment]
@JanTvrdik I agree. Will you try to implement it? I remember you did some research once.

**Comment by JanTvrdik** [comment]
> Will you try to implement it? 

Here or in nette/application?

> I remember you did some research once.

Really? I don't :smile:

**Comment by dg** [comment]
Of course in nette/application, this repo is not used.

**Comment by fprochazka** [comment]
@JanTvrdik I remember it too, you've made some nice table with comparision of the use-cases :)

**Comment by JanTvrdik** [comment]
Found it https://github.com/nette/nette/pull/1196#issuecomment-171288662
