### ISSUE TITLE
Forced HTTP

### ISSUE THREAD

**Issue by TawreCZ** [nette/routing#7]
When I setted nginx on https connections nette routes redirecting to http version in default configuration.

Can be resolved with forcing https on specific routes or forcing https globally, but why is that behavior preffered?

And what I need to do to support both versions secure and non-secure on same route?

**Comment by milo** [comment]
`http://` and `https://` are two different URLs for search engines, so redirect prevents before duplicit content.

Use [forum](http://forum.nette.org) to ask, or search it, it has been solved there already. This is issues tracker.
